### ISSUE TITLE
error running the package

### ISSUE THREAD

**Issue by sarincm** [Prestaul/skeemas-markdown-validation#1]
hi
i want to use this package to validate my md files..i was trying to run the index.test.js in test folder to get the understanding about this...but i am getting a error 
`describe('skeemas-markdown-validation plugin', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (.....\tests\index.test.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
   at Module.load (internal/modules/cjs/loader.js:812:32)
   at Function.Module._load (internal/modules/cjs/loader.js:724:14)
   at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
   at internal/main/run_main_module.js:17:11`

is there any node package i missing to install..or any other error..please help me

thanks

**Comment by Prestaul** [comment]
You need to have a test framework that adds a `describe` method or you need to drop the outer `describe` call. Have a look at `mocha` or `jest` if you are looking for a testing framework.

**Comment by sarincm** [comment]
@Prestaul thank you very much..i found it myself....anyway thanks for update
